# Generated by Django 3.1 on 2021-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
