# Generated by Django 3.1 on 2021-03-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
