# Generated by Django 3.1 on 2021-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210304_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(blank=True, choices=[('Billing Address', 'Billing Address'), ('Shipping Address', 'Shipping Address')], max_length=20, null=True),
        ),
    ]
